version: '4.18.0'

networks:
  bookkeeping_docker_net:

services:
  php:
    build:
      context: ./
      dockerfile: ./php/Dockerfile
    container_name: php-container
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/project
    depends_on:
      - mongo
    networks:
      bookkeeping_docker_net:
        aliases:
          - php-fpm

  nginx:
    image: nginx
    container_name: nginx-container
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    depends_on:
      - php
      - mongodb
    networks:
      bookkeeping_docker_net:
        aliases:
          - nginx-web

  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongodb:/data/db
    networks:
      bookkeeping_docker_net:
        aliases:
          - mongodb

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'root'
      ME_CONFIG_MONGODB_ADMINPASSWORD: '0000'
      ME_CONFIG_MONGODB_URL: mongodb://root:0000@mongo:27017/


  node:
    image: node:latest
    user: 'node'
    container_name: node-container
    working_dir: /var/www/project
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/var/www/project
    expose:
      - 8000
    command: 'npm run watch'
    networks:
      bookkeeping_docker_net:
        aliases:
          - node