parameters:
    mongodb_url: '%env(MONGODB_URL)%'
    mongodb_db: '%env(MONGODB_DB)%'
    oauth_google_client_id: '%env(OAUTH_GOOGLE_CLIENT_ID)%'
    oauth_google_secret: '%env(OAUTH_GOOGLE_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Document/'
            - '../src/Kernel.php'

    App\Stage\WriteStage:
        decorates: api_platform.graphql.resolver.stage.write
